<p>
	<span><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></span>
</p>
<p>
	<?php echo Mage::helper('rede_adquirencia')->getLogoHtml(100) ?>
</p>
<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
    <tbody>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <tr>
            <th><strong><?php echo $this->escapeHtml($_label)?>:</strong></th>
        </tr>
        <tr>
            <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>
<?php echo $this->getChildHtml()?>
