<?php
	$_helper = Mage::helper('rede_adquirencia');
	$order = $this->getOrder();
?>
<div class="page-title">
    <h1>
    	<?php echo $this->escapeHtml($_helper->__('Your order #%s is %s.', $order->getRealOrderId(), $_helper->__($order->getStatusLabel()))) ?>
    </h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<p>
	<?php echo $_helper->__('Your payment was not proccessed.') ?>
</p>
<?php if ($this->canReorder()): ?>
<p>
	<?php echo $_helper->__('To retry the payment for the order, please click in the link below:') ?>
</p>
<p class="button-container">
    <button type="button" title="<?php echo $_helper->__('Reorder') ?>"
    	class="button btn-continue" onclick="window.location='<?php echo $this->getReorderUrl() ?>';">
    	<span>
    		<span>
    			<?php echo $_helper->__('Reorder') ?>
    		</span>
    	</span>
    </button>
</p>
<?php endif; ?>
